#!/bin/sh

FPS=""
OPT=""

if ! which seom-x264 &> /dev/null; then
	echo "You need to install seom-x264"
	exit -1
fi

if [ ${#} -ne 2 ]; then
	echo "Usage: $ ${0} [src dir] [dst dir]"
	exit 1;
fi

if [ ! -d ${1} -o ! -d ${2} ]; then
	echo "Source or destination directories don't exist"
	exit 1
fi

if [ -e "$HOME/.seom/backup" ]; then
	source "$HOME/.seom/backup"
fi

files=$(ls ${1}/*.seom 2> /dev/null)
for src in ${files}; do
	tmp=${src##*/}

	tmp=$(mktemp -p ${1} ${tmp}-XXXXXX)
	rm ${tmp}
	mv -f "${src}" "${tmp}" # FIXME: don't overwrite existing files
done

files=$(ls ${1}/*.seom-?????? 2> /dev/null)
for src in ${files}; do
	tmp=${src##*/}
	dst="${2}/${tmp%%.seom-??????}--$(stat -c %y ${src} | sed 's#\..*##' | sed 's# #--#').mp4"
	
	echo -n "Processing '${src}' "

	unset int
	trap 'int=1' SIGINT
	if [ "${FPS}" = "" ]; then
		seom-x264 -o ${dst} ${OPT} ${src} &> /dev/null
	else
		seom-filter ${src} -r ${FPS} | seom-x264 -o ${dst} ${OPT} stdin.y4m &> /dev/null
	fi

	if [ ${?} -eq 0 ] && [ -z ${int} ]; then
		rm ${src}
		echo "..."
	else
		rm ${dst}
		echo "... failed"
	fi
done
